### ISSUE TITLE
Currency validator naming

### ISSUE THREAD

**Issue by jxom** [hugomd/joi-currency-code#1]
Shouldn't it be `.currencyCode()`, instead of `.currency()`? 

I think `.currency()` would validate something like `$5.00`. Thus `.currencyCode()` would validate `aud`, `usd`, etc.

**Comment by hugomd** [comment]
@jxom Agreed, I think the resolution would be to modify [`is-currency`](https://github.com/hugomd/is-currency) to allow `currency()` to validate both currency codes _and_ symbols, while `currencyCode()` and `currencySymbol()` would validate codes and symbols respectively.

Thanks for raising this ✌️

**Comment by hugomd** [comment]
@jxom I've raised this in [`is-currency`](https://github.com/hugomd/is-currency/issues/2).
