### ISSUE TITLE
hapi/joi Deprecated

### ISSUE THREAD

**Issue by milad2golnia** [hugomd/joi-currency-code#22]
Hi! 
`hapi/joi` is deprecated now, please update it to work with `joi` package instead.
Currently it's not working and raises following error:
```
Uncaught TypeError: Joi.string is not a function
```

**Comment by hugomd** [comment]
I've published version `3.0.2` with `joi` instead of `hapi/joi`, please raise another issue if you have any problems with it, or feel free to raise a pull request.
